stages:
  - prepare
  - run

.default_cache:
  cache:
    paths:
      - 2020/.bundle/config
      - 2020/vendor/bundle/
    policy: pull-push


bundle:
  extends: .default_cache
  stage: prepare
  script:
    - cd 2020
    - bundle config set clean 'true' --local
    - bundle config set path 'vendor/bundle' --local
    - bundle install

aoc-2020:
  extends: .default_cache
  cache:
    policy: pull
  stage: run
  script:
    - cd 2020
    - bundle exec ruby all.rb
