stages:
  - prepare
  - run

bundle:
  stage: prepare
  script:
    - cd 2020
    - bundle config set clean 'true' --local
    - bundle config set path 'vendor/bundle' --local
    - bundle install

aoc-2020:
  stage: run
  script:
    - cd 2020
    - bundle exec ruby all.rb
