stages:
  - 'prepare bundle'
  # - 'prepare python'
  - run
  - report

.default_cache:
  cache:
    paths:
      - 2020/.bundle/config
      - 2020/vendor/bundle/
      - 2021/.bundle/config
      - 2021/vendor/bundle/
    policy: pull-push


bundle:
  extends: .default_cache
  stage: 'prepare bundle'
  script:
    - cd 2020
    - bundle config set clean 'true' --local
    - bundle config set path 'vendor/bundle' --local
    - bundle install
    - cd ../2021
    - bundle config set clean 'true' --local
    - bundle config set path 'vendor/bundle' --local
    - bundle install

# pip:
#   extends: .default_cache
#   stage: 'prepare python'
#   script:
#     - cd 2020
#     - pip3.6 install --user anybadge

aoc-2020:
  extends: .default_cache
  cache:
    policy: pull
  stage: run
  script:
    - cd 2020
    - bundle exec ruby all.rb > output.txt
    - cat output.txt
  artifacts:
    paths:
      - 2020/output.txt

aoc-2021:
  extends: .default_cache
  cache:
    policy: pull
  stage: run
  script:
    - cd 2021
    - bundle exec ruby all.rb > output.txt
    - cat output.txt
  artifacts:
    paths:
      - 2021/output.txt

create_badge_svg:
  stage: report
  script:
    - commits=$(git rev-list --all --count)
    - pip3.6 install --user anybadge
    - ~/.local/bin/anybadge -l commits -v $commits -f commits.svg -c green
  artifacts:
    paths:
      - commits.svg
    when: always
    expire_in: 4 weeks
